export default {
  "login": "AdroitMachine",
  "id": 10528925,
  "node_id": "MDQ6VXNlcjEwNTI4OTI1",
  "avatar_url": "https://avatars.githubusercontent.com/u/10528925?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AdroitMachine",
  "html_url": "https://github.com/AdroitMachine",
  "followers_url": "https://api.github.com/users/AdroitMachine/followers",
  "following_url": "https://api.github.com/users/AdroitMachine/following{/other_user}",
  "gists_url": "https://api.github.com/users/AdroitMachine/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AdroitMachine/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AdroitMachine/subscriptions",
  "organizations_url": "https://api.github.com/users/AdroitMachine/orgs",
  "repos_url": "https://api.github.com/users/AdroitMachine/repos",
  "events_url": "https://api.github.com/users/AdroitMachine/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AdroitMachine/received_events",
  "type": "User",
  "site_admin": false,
  "name": "adroit_machine",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "Hi, I'm adroit_machine",
  "twitter_username": null,
  "public_repos": 52,
  "public_gists": 3,
  "followers": 0,
  "following": 1,
  "created_at": "2015-01-14T09:21:42Z",
  "updated_at": "2021-01-13T14:36:57Z"
}